/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DealerRouteImport } from './routes/dealer'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OwnerIndexRouteImport } from './routes/owner.index'
import { Route as DealerIndexRouteImport } from './routes/dealer.index'
import { Route as OwnerNewRouteImport } from './routes/owner.new'
import { Route as OwnerHistoryRouteImport } from './routes/owner.history'
import { Route as DealerSavedRouteImport } from './routes/dealer.saved'
import { Route as DealerAnalyticsRouteImport } from './routes/dealer.analytics'
import { Route as OwnerVehicleKeyRouteImport } from './routes/owner.vehicle.$key'
import { Route as DealerVehicleIdRouteImport } from './routes/dealer.vehicle.$id'

const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DealerRoute = DealerRouteImport.update({
  id: '/dealer',
  path: '/dealer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerRoute,
} as any)
const DealerIndexRoute = DealerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DealerRoute,
} as any)
const OwnerNewRoute = OwnerNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerHistoryRoute = OwnerHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => OwnerRoute,
} as any)
const DealerSavedRoute = DealerSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => DealerRoute,
} as any)
const DealerAnalyticsRoute = DealerAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DealerRoute,
} as any)
const OwnerVehicleKeyRoute = OwnerVehicleKeyRouteImport.update({
  id: '/vehicle/$key',
  path: '/vehicle/$key',
  getParentRoute: () => OwnerRoute,
} as any)
const DealerVehicleIdRoute = DealerVehicleIdRouteImport.update({
  id: '/vehicle/$id',
  path: '/vehicle/$id',
  getParentRoute: () => DealerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dealer': typeof DealerRouteWithChildren
  '/login': typeof LoginRoute
  '/owner': typeof OwnerRouteWithChildren
  '/dealer/analytics': typeof DealerAnalyticsRoute
  '/dealer/saved': typeof DealerSavedRoute
  '/owner/history': typeof OwnerHistoryRoute
  '/owner/new': typeof OwnerNewRoute
  '/dealer/': typeof DealerIndexRoute
  '/owner/': typeof OwnerIndexRoute
  '/dealer/vehicle/$id': typeof DealerVehicleIdRoute
  '/owner/vehicle/$key': typeof OwnerVehicleKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dealer/analytics': typeof DealerAnalyticsRoute
  '/dealer/saved': typeof DealerSavedRoute
  '/owner/history': typeof OwnerHistoryRoute
  '/owner/new': typeof OwnerNewRoute
  '/dealer': typeof DealerIndexRoute
  '/owner': typeof OwnerIndexRoute
  '/dealer/vehicle/$id': typeof DealerVehicleIdRoute
  '/owner/vehicle/$key': typeof OwnerVehicleKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dealer': typeof DealerRouteWithChildren
  '/login': typeof LoginRoute
  '/owner': typeof OwnerRouteWithChildren
  '/dealer/analytics': typeof DealerAnalyticsRoute
  '/dealer/saved': typeof DealerSavedRoute
  '/owner/history': typeof OwnerHistoryRoute
  '/owner/new': typeof OwnerNewRoute
  '/dealer/': typeof DealerIndexRoute
  '/owner/': typeof OwnerIndexRoute
  '/dealer/vehicle/$id': typeof DealerVehicleIdRoute
  '/owner/vehicle/$key': typeof OwnerVehicleKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dealer'
    | '/login'
    | '/owner'
    | '/dealer/analytics'
    | '/dealer/saved'
    | '/owner/history'
    | '/owner/new'
    | '/dealer/'
    | '/owner/'
    | '/dealer/vehicle/$id'
    | '/owner/vehicle/$key'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dealer/analytics'
    | '/dealer/saved'
    | '/owner/history'
    | '/owner/new'
    | '/dealer'
    | '/owner'
    | '/dealer/vehicle/$id'
    | '/owner/vehicle/$key'
  id:
    | '__root__'
    | '/'
    | '/dealer'
    | '/login'
    | '/owner'
    | '/dealer/analytics'
    | '/dealer/saved'
    | '/owner/history'
    | '/owner/new'
    | '/dealer/'
    | '/owner/'
    | '/dealer/vehicle/$id'
    | '/owner/vehicle/$key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DealerRoute: typeof DealerRouteWithChildren
  LoginRoute: typeof LoginRoute
  OwnerRoute: typeof OwnerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dealer': {
      id: '/dealer'
      path: '/dealer'
      fullPath: '/dealer'
      preLoaderRoute: typeof DealerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/': {
      id: '/owner/'
      path: '/'
      fullPath: '/owner/'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/dealer/': {
      id: '/dealer/'
      path: '/'
      fullPath: '/dealer/'
      preLoaderRoute: typeof DealerIndexRouteImport
      parentRoute: typeof DealerRoute
    }
    '/owner/new': {
      id: '/owner/new'
      path: '/new'
      fullPath: '/owner/new'
      preLoaderRoute: typeof OwnerNewRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/history': {
      id: '/owner/history'
      path: '/history'
      fullPath: '/owner/history'
      preLoaderRoute: typeof OwnerHistoryRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/dealer/saved': {
      id: '/dealer/saved'
      path: '/saved'
      fullPath: '/dealer/saved'
      preLoaderRoute: typeof DealerSavedRouteImport
      parentRoute: typeof DealerRoute
    }
    '/dealer/analytics': {
      id: '/dealer/analytics'
      path: '/analytics'
      fullPath: '/dealer/analytics'
      preLoaderRoute: typeof DealerAnalyticsRouteImport
      parentRoute: typeof DealerRoute
    }
    '/owner/vehicle/$key': {
      id: '/owner/vehicle/$key'
      path: '/vehicle/$key'
      fullPath: '/owner/vehicle/$key'
      preLoaderRoute: typeof OwnerVehicleKeyRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/dealer/vehicle/$id': {
      id: '/dealer/vehicle/$id'
      path: '/vehicle/$id'
      fullPath: '/dealer/vehicle/$id'
      preLoaderRoute: typeof DealerVehicleIdRouteImport
      parentRoute: typeof DealerRoute
    }
  }
}

interface DealerRouteChildren {
  DealerAnalyticsRoute: typeof DealerAnalyticsRoute
  DealerSavedRoute: typeof DealerSavedRoute
  DealerIndexRoute: typeof DealerIndexRoute
  DealerVehicleIdRoute: typeof DealerVehicleIdRoute
}

const DealerRouteChildren: DealerRouteChildren = {
  DealerAnalyticsRoute: DealerAnalyticsRoute,
  DealerSavedRoute: DealerSavedRoute,
  DealerIndexRoute: DealerIndexRoute,
  DealerVehicleIdRoute: DealerVehicleIdRoute,
}

const DealerRouteWithChildren =
  DealerRoute._addFileChildren(DealerRouteChildren)

interface OwnerRouteChildren {
  OwnerHistoryRoute: typeof OwnerHistoryRoute
  OwnerNewRoute: typeof OwnerNewRoute
  OwnerIndexRoute: typeof OwnerIndexRoute
  OwnerVehicleKeyRoute: typeof OwnerVehicleKeyRoute
}

const OwnerRouteChildren: OwnerRouteChildren = {
  OwnerHistoryRoute: OwnerHistoryRoute,
  OwnerNewRoute: OwnerNewRoute,
  OwnerIndexRoute: OwnerIndexRoute,
  OwnerVehicleKeyRoute: OwnerVehicleKeyRoute,
}

const OwnerRouteWithChildren = OwnerRoute._addFileChildren(OwnerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DealerRoute: DealerRouteWithChildren,
  LoginRoute: LoginRoute,
  OwnerRoute: OwnerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
