export function ReportFooter() {
  return (
    <div className="space-y-4 pt-2">
      <div className="space-y-1 text-[12px] text-[color:var(--neutral-muted)]">
        <p>
          Report generated by Honda Value Passport · Powered by AppTestify ×
          IQLEXA Technologies.
        </p>
        <p>
          Values are indicative estimates based on market data as of June 2026.
          Final price determined by dealer inspection.
        </p>
      </div>
    </div>
  );
}
