import { Download, Share2 } from "lucide-react";

export function ReportFooter() {
  return (
    <div className="space-y-4 pt-2">
      <div className="flex flex-wrap gap-3">
        <button className="inline-flex h-11 items-center gap-2 rounded-[8px] bg-[color:var(--honda-red)] px-5 text-[14px] font-medium text-white transition hover:bg-[color:var(--honda-red-hover)]">
          <Download size={16} /> Download PDF Report
        </button>
        <button className="inline-flex h-11 items-center gap-2 rounded-[8px] border border-[color:var(--honda-red)] bg-white px-5 text-[14px] font-medium text-[color:var(--honda-red)] transition hover:bg-[color:var(--honda-red)]/5">
          <Share2 size={16} /> Share Report
        </button>
      </div>
      <div className="space-y-1 text-[12px] text-[color:var(--neutral-muted)]">
        <p>
          Report generated by Honda Value Passport · Powered by AppTestify ×
          IQLEXA Technologies.
        </p>
        <p>
          Values are indicative estimates based on market data as of June 2026.
          Final price determined by dealer inspection.
        </p>
      </div>
    </div>
  );
}
